# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Python
tagline:             'python'
description:         'A Tour of Python'
url:                 https://www.python.org
baseurl:             '/py-tour'
paginate:            20
resource:            '/lessons'

# About/contact
author:
  name:              Georgekutty Joyes
  url:               https://github.com/george-kj
  email:             georgekuttyjoyes@gmail.com


# Github repo
github:
  repo:             https://github.com/george-kj/lanyon               
  tag:              1.0.0